# Use goreman to run `go get github.com/mattn/goreman`
# Change the path of bin/zero if zero is located elsewhere

zero1: ./zero --name infra1 --listen-client-urls http://127.0.0.1:2379 --advertise-client-urls http://127.0.0.1:2379 --listen-peer-urls http://127.0.0.1:12380  --advertise-peer-urls http://127.0.0.1:12380 --initial-cluster-token zero-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380' --initial-cluster-state new --listen-grpc 127.0.0.1:3401 --listen-http 127.0.0.1:13401

#proxy: bin/zero grpc-proxy start --endpoints=127.0.0.1:2379,127.0.0.1:22379,127.0.0.1:32379 --listen-addr=127.0.0.1:23790 --advertise-client-url=127.0.0.1:23790 --enable-pprof

# A learner node can be started using Procfile.learner
